### ISSUE TITLE
LockonpluginKK setting camera angles

### ISSUE THREAD

**Issue by yifu3507** [Keelhauled/KoikatuPlugins#10]
Attempting to set other camera targets and apparently it didn't work and when i press the desired lock on places when target gui is shown it didn't lock on.

**Comment by Keelhauled** [comment]
I think i disabled most of the target gui feature and kept it for bone debugging or something. So it shouldn't be working.

**Comment by yifu3507** [comment]
> I think i disabled most of the target gui feature and kept it for bone debugging or something. So it shouldn't be working.

Hmm...will you re-open the target gui feature in near future bro?

**Comment by Keelhauled** [comment]
Probably not because i wasn't using it and it looked pretty ugly, instead i added the ability to lock on to FK/IK points. The point of the feature was to be able to easily edit FK/IK bones anyway.

**Comment by yifu3507** [comment]
> Probably not because i wasn't using it and it looked pretty ugly, instead i added the ability to lock on to FK/IK points. The point of the feature was to be able to easily edit FK/IK bones anyway.

So...editing the dll file u mean?
Apparently it didn't work for me though cos after i edited the dll file it won't recognize in both game and charastudio....

Although i personaly prefer to use the target gui tbh although it's rather a mess to look at lol.

**Comment by Keelhauled** [comment]
It wasn't for studio only in HS.
