### ISSUE TITLE
UnlockHPositions causes lock up in H

### ISSUE THREAD

**Issue by DeathWeasel1337** [Keelhauled/KoikatuPlugins#6]
When "Unlock all positions" is enabled, entering a yuri H scene locks up the game. Additionally, it unlocks all the positions in other modes such as peeping and solo which prevents the player from leaving the H scene. Ideally, a check should be performed to see if the player is in the correct mode before generating the list of positions.

**Comment by PolarManne** [comment]
Adding onto this, it also causes 3P mode to lock up the game
