### ISSUE TITLE
Anti-Aliasing is only Multisampling (GraphicsSettings)

### ISSUE THREAD

**Issue by GenesisAria** [Keelhauled/KoikatuPlugins#7]
Ever since using new BepInEx, i've been completely unable to inject anti-aliasing from my drivers, of which i always used supersampling, because the game is light enough for me to do so.  Multisampling is nice and all, but if AA is not set to at least adaptive (for transparencies as well), if not supersampling (for everything), i cannot override it, and i'm stuck with jaggies infesting hair and eyes etc.

**Comment by Keelhauled** [comment]
If you think BepInEx is the cause you should make an issue on that repo instead. In case this was about getting me to add more anti-aliasing options to GraphicsSettings, not interested.
